# PostgreSQL container called 'pg'
version: '3.1'

services:
  pg:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    ports:
      - '5432'
